; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Castlevania 2:
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_PITCH_TRACK = 1

.export _music_data_castlevania_2:=music_data_castlevania_2

music_data_castlevania_2:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Bloody Tears
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_castlevania_2
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env12,@env11,@env18,@env0 ; 00 : VoiceRelease
	.word @env10,@env11,@env18,@env13 ; 01 : VoiceSoftAttack
	.word @env26,@env11,@env18,@env0 ; 02 : VoiceFadeIn2
	.word @env15,@env11,@env21,@env0 ; 03 : VoiceFadeIn
	.word @env24,@env11,@env21,@env0 ; 04 : VoiceShort
	.word @env19,@env11,@env22,@env13 ; 05 : Lead
	.word @env8,@env6,@env28,@env0 ; 06 : LeadOctave
	.word @env25,@env20,@env18,@env0 ; 07 : Snare1
	.word @env9,@env11,@env1,@env0 ; 08 : Harpsichord-Intro2
	.word @env27,@env6,@env18,@env0 ; 09 : Harpsichord-Intro1
	.word @env5,@env11,@env2,@env13 ; 0a : LeadOctave2
	.word @env4,@env16,@env18,@env0 ; 0b : Snare2
	.word @env17,@env11,@env3,@env0 ; 0c : LeadPreIntro1
	.word @env14,@env11,@env1,@env0 ; 0d : Harpsichord-Alt2
	.word @env17,@env11,@env1,@env0 ; 0e : LeadPreIntro2
	.word @env7,@env11,@env18,@env0 ; 0f : Bass
	.word @env23,@env11,@env3,@env0 ; 10 : Harpsichord-Alt1

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c1,$c0,$00,$01
@env2:
	.byte $c2,$c1,$00,$01
@env3:
	.byte $c2,$c0,$00,$01
@env4:
	.byte $00,$c6,$c2,$c3,$c1,$00,$04
@env5:
	.byte $00,$c8,$c6,$c5,$03,$c4,$04,$c3,$c3,$c5,$c5,$c4,$c4,$c2,$00,$0d
@env6:
	.byte $b4,$c0,$00,$01
@env7:
	.byte $00,$cf,$7f,$00,$02
@env8:
	.byte $0b,$c8,$c8,$c6,$c5,$03,$c4,$02,$c3,$00,$08,$c2,$00,$0b
@env9:
	.byte $00,$c6,$c5,$c4,$03,$c3,$00,$05
@env10:
	.byte $08,$c7,$c8,$c7,$c6,$c5,$00,$05,$c2,$00,$08
@env11:
	.byte $c0,$7f,$00,$01
@env12:
	.byte $06,$c3,$c2,$c1,$00,$03,$c2,$00,$06
@env13:
	.byte $00,$c0,$0b,$c0,$c0,$c1,$c1,$c0,$c0,$bf,$bf,$00,$03
@env14:
	.byte $00,$c8,$c7,$c6,$c6,$c5,$c5,$c4,$00,$07
@env15:
	.byte $0c,$c2,$03,$c3,$03,$c4,$03,$c5,$c5,$c6,$00,$09,$c5,$c5,$c4,$00,$0e
@env16:
	.byte $c0,$c1,$c4,$00,$02
@env17:
	.byte $08,$c8,$c7,$c6,$c6,$c5,$00,$05,$c2,$00,$08
@env18:
	.byte $7f,$00,$00
@env19:
	.byte $09,$c4,$c5,$03,$c4,$0e,$c3,$00,$06,$c2,$00,$09
@env20:
	.byte $c0,$c8,$ca,$cb,$ca,$cb,$cc,$ce,$00,$07
@env21:
	.byte $c1,$7f,$00,$00
@env22:
	.byte $c0,$c1,$00,$01
@env23:
	.byte $00,$c7,$c6,$c5,$c5,$c4,$c4,$c3,$00,$07
@env24:
	.byte $00,$c4,$c5,$03,$c4,$00,$04
@env25:
	.byte $00,$ce,$c8,$c3,$c4,$c3,$c1,$00,$06
@env26:
	.byte $09,$c4,$c5,$c6,$c7,$c7,$c8,$00,$06,$c2,$00,$09
@env27:
	.byte $00,$c6,$c6,$c5,$c4,$c4,$c3,$c2,$00,$07
@env28:
	.byte $c2,$c2,$c1,$00,$02

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$0b,$0f,$40 ; 00 BassDrum (Pitch:15)
	.byte $03+.lobyte(FAMISTUDIO_DPCM_PTR),$17,$0e,$40 ; 01 Snare (Pitch:14)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ref1:
	.byte $92
@song0ref2:
	.byte $23, $8b, $1e, $8b, $2a, $8b, $1e, $8b
@song0ref10:
	.byte $28, $8b, $1e, $8b, $26
@song0ref15:
	.byte $8b, $1e, $8b, $25, $8b, $1e, $8b, $26, $8b, $1e, $8b, $25, $8b, $1e, $8b, $23
	.byte $41, $0b
	.word @song0ref15
	.byte $41, $0c
	.word @song0ref10
@song0ref37:
	.byte $21, $8b, $1e, $8b, $25, $8b, $1e, $8b, $23, $8b, $1e, $8b, $48
	.byte $41, $1d
	.word @song0ref2
	.byte $41, $0b
	.word @song0ref15
	.byte $41, $0c
	.word @song0ref10
	.byte $41, $0c
	.word @song0ref37
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song0ref66:
	.byte $8a
@song0ref67:
	.byte $25, $8f, $45, $87, $28, $87, $45, $81, $26, $8f, $45, $87, $8c, $19, $89, $45, $17, $89, $45, $19, $89, $45, $1a, $91
	.byte $45, $85, $1c, $91, $45, $85, $94, $1e, $b5, $8a, $25, $97, $45, $8d, $2a, $97, $45, $8d, $26, $af, $45, $9f, $25, $8f
	.byte $45, $87, $23, $8f, $45, $87, $48
	.byte $41, $0c
	.word @song0ref67
@song0ref125:
	.byte $8c, $1c, $89, $45, $1a, $89, $45, $1c, $89, $45, $1e, $91, $45, $85, $1f, $91, $45, $85, $21, $91, $45, $85, $23, $91
	.byte $45, $85, $86, $25, $95, $45, $80, $25, $8d, $86, $25, $9d, $45, $87, $80, $25, $99, $86, $23, $97, $80, $23, $8d, $86
	.byte $23, $9d, $45, $87, $80, $23, $99, $48
	.byte $41, $33
	.word @song0ref66
	.byte $48
	.byte $41, $0c
	.word @song0ref67
	.byte $41, $24
	.word @song0ref125
	.byte $88, $22, $8f, $80, $22, $87, $88, $23, $8f, $80, $23, $87, $88, $25, $8f, $80, $25, $87, $88, $28, $8f, $80, $28, $87
	.byte $48, $7f, $82, $1c, $89, $45, $78, $1c, $8d, $7f
@song0ref225:
	.byte $80, $1c, $87, $45, $7c
@song0ref230:
	.byte $82, $1a, $8b, $84, $1a, $8f, $45, $87, $82, $26, $8b, $84, $26, $85, $45, $83, $7f, $82, $1c, $89, $45, $84, $1c, $8d
	.byte $41, $12
	.word @song0ref225
	.byte $78, $1c, $8d, $7f, $80, $1c, $87, $45
	.byte $41, $0c
	.word @song0ref230
	.byte $a0, $1a, $8b, $26, $8b, $19, $8b, $25, $8b, $17, $8b, $23, $8b, $15, $8b, $21, $8b, $48, $82
@song0ref287:
	.byte $1c, $89, $45, $7d, $1c, $8b, $43, $1a, $1a, $89, $43, $26, $26, $89, $7c, $87, $7d, $87, $7e, $87, $7f, $8d, $45, $8f
	.byte $41, $11
	.word @song0ref287
	.byte $41, $11
	.word @song0ref287
	.byte $98, $26, $93, $45, $83, $28, $93, $45, $83, $25, $89, $45, $26, $9d, $45, $87, $48
	.byte $41, $1d
	.word @song0ref1
	.byte $41, $0b
	.word @song0ref15
	.byte $41, $0c
	.word @song0ref10
	.byte $41, $0c
	.word @song0ref37
	.byte $48
	.byte $41, $1d
	.word @song0ref2
	.byte $41, $0b
	.word @song0ref15
	.byte $41, $0c
	.word @song0ref10
	.byte $41, $0c
	.word @song0ref37
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ref362:
	.byte $4e, $01, $90
@song0ref365:
	.byte $2f, $8b, $2a, $8b, $36, $8b, $2a, $8b
@song0ref373:
	.byte $34, $8b, $2a, $8b, $32
@song0ref378:
	.byte $8b, $2a, $8b, $31, $8b, $2a, $8b, $32, $8b, $2a, $8b, $31, $8b, $2a, $8b, $2f
	.byte $41, $0b
	.word @song0ref378
	.byte $41, $0c
	.word @song0ref373
@song0ref400:
	.byte $2d, $8b, $2a, $8b, $31, $8b, $2a, $8b, $2f, $8b, $2a, $8b, $4e, $01
	.byte $41, $1d
	.word @song0ref365
	.byte $41, $0b
	.word @song0ref378
	.byte $41, $0c
	.word @song0ref373
	.byte $41, $0c
	.word @song0ref400
@song0ch1loop:
@song0ref427:
	.byte $4e, $00, $8a, $28
@song0ref431:
	.byte $8f, $45, $87, $2d, $87, $45, $81, $2a, $c7, $45, $b1
@song0ref442:
	.byte $28, $8f, $45, $87, $26, $8f, $45, $87, $28, $97, $45, $8d, $2d, $97, $45, $8d, $2a, $af, $45, $9f
	.byte $41, $09
	.word @song0ref442
	.byte $41, $0f
	.word @song0ref431
@song0ref468:
	.byte $2a, $8f, $45, $87, $86, $2b, $95, $45, $80, $2b, $8d, $86, $2d, $9d, $45, $87, $80, $2d, $99, $86, $2a, $97, $80, $2a
	.byte $8d, $86, $2b, $9d, $45, $87, $80, $2b, $99
	.byte $41, $20
	.word @song0ref427
	.byte $41, $09
	.word @song0ref442
	.byte $41, $0f
	.word @song0ref431
	.byte $41, $0f
	.word @song0ref468
	.byte $88, $2a, $8f, $80, $2a, $87, $88, $2c, $8f, $80, $2c, $87, $88, $2e, $8f, $80, $2e, $87, $88, $31, $8f, $80, $31, $87
	.byte $7f, $82, $25, $89, $45, $78, $25, $8d, $7f
@song0ref546:
	.byte $80, $25, $87, $45, $7c
@song0ref551:
	.byte $82, $23, $8b, $84, $23, $8f, $45, $87, $82, $2f, $8b, $84, $2f, $85, $45, $83, $7f, $82, $25, $89, $45, $84, $25, $8d
	.byte $41, $12
	.word @song0ref546
	.byte $78, $25, $8d, $7f, $80, $25, $87, $45
	.byte $41, $0c
	.word @song0ref551
	.byte $4e, $01, $9a, $26, $8b, $32, $8b, $25, $8b, $31, $8b, $23, $8b, $2f, $8b, $21, $8b, $2d, $8b, $4e, $00, $82
@song0ref611:
	.byte $25, $89, $45, $7d, $25, $8b, $43, $23, $23, $89, $43, $2f, $2f, $89, $7c, $87, $7d, $87, $7e, $87, $7f, $8d, $45, $8f
	.byte $41, $11
	.word @song0ref611
	.byte $41, $11
	.word @song0ref611
	.byte $4e, $01, $9c, $32, $93, $45, $83, $34, $93, $45, $83, $31, $89, $45, $32, $9d, $45, $87
	.byte $41, $1d
	.word @song0ref362
	.byte $41, $0b
	.word @song0ref378
	.byte $41, $0c
	.word @song0ref373
	.byte $41, $0c
	.word @song0ref400
	.byte $4e, $01
	.byte $41, $1d
	.word @song0ref365
	.byte $41, $0b
	.word @song0ref378
	.byte $41, $0c
	.word @song0ref373
	.byte $41, $0c
	.word @song0ref400
	.byte $42
	.word @song0ch1loop
@song0ch2:
	.byte $9e
@song0ref689:
	.byte $17, $ff, $dd, $12, $ed, $1e, $ed, $17, $ff, $dd, $12, $ed, $1e, $ed
@song0ch2loop:
	.byte $17, $97, $00, $23, $89, $00, $17, $8b, $00, $8b, $17, $8b, $23, $89, $00, $8d, $17, $97, $00, $23, $89, $00, $8d, $17
	.byte $89, $00, $8d
@song0ref731:
	.byte $23, $89, $00, $8d, $15, $97, $00, $21, $89, $00, $15, $89, $00, $8d, $15, $89, $00, $21, $8b, $00, $8b, $15, $89, $00
	.byte $8d
@song0ref756:
	.byte $21, $89, $00, $8d, $15, $89, $00, $15, $89, $00, $21, $8b, $00, $8b, $13, $97, $00, $1f, $89, $00
@song0ref776:
	.byte $13, $89, $00, $8d, $13, $89, $00, $1f, $89, $00, $8d, $13, $89, $00, $13, $89, $00, $1f, $89, $00, $8d, $13, $8b, $00
	.byte $8b, $1f
@song0ref802:
	.byte $89, $00, $8d
@song0ref805:
	.byte $12, $89, $00, $12, $89, $00, $1e, $89, $00, $12, $89, $00, $8d, $12, $89, $00, $1e, $89, $00, $8d, $12, $89, $00, $8d
	.byte $1e
	.byte $41, $0c
	.word @song0ref802
	.byte $8d, $17, $97, $00, $23, $8b, $17, $89, $00, $8d, $17, $8b, $23, $89, $00, $8d, $17, $89, $00, $17, $89, $00, $23, $8b
	.byte $00, $8b, $17, $8b, $00, $8b
	.byte $41, $12
	.word @song0ref731
	.byte $89, $00, $8d, $15, $8b, $00, $8b
	.byte $41, $0b
	.word @song0ref756
	.byte $89, $00, $8d, $13, $97, $00, $1f, $8b
	.byte $41, $16
	.word @song0ref776
	.byte $89, $00, $8d, $1f, $8b, $00, $8b
	.byte $41, $0a
	.word @song0ref805
	.byte $8b, $00, $8b, $12, $89, $00, $1e, $89, $00, $8d, $12, $8b, $1e, $89, $00, $14, $89, $00, $20, $89, $00, $16, $89, $00
	.byte $22, $89, $00, $19, $89, $00, $25, $89, $00
@song0ref930:
	.byte $17, $a5, $00, $17, $a5, $00, $17, $89, $00, $23, $8b, $15, $a5, $00, $15, $a5, $00, $15, $8b, $21, $89
@song0ref951:
	.byte $00, $13, $a5, $00, $13, $a5, $00, $13, $89, $00, $1f
@song0ref962:
	.byte $89, $00, $15, $a5, $00, $15, $a5, $00, $15, $89, $00, $21, $8b
	.byte $41, $0a
	.word @song0ref930
	.byte $41, $09
	.word @song0ref962
	.byte $97
	.byte $41, $0e
	.word @song0ref951
	.byte $97, $00, $21, $97, $00, $15, $89, $00, $15, $89, $00, $21, $97, $00
	.byte $41, $0e
	.word @song0ref689
	.byte $42
	.word @song0ch2loop
@song0ch3:
	.byte $ff, $ff, $ff, $89, $8e, $15, $8d, $00, $a3, $ff, $ff, $ff, $89
@song0ref1018:
	.byte $15, $8d, $00, $89, $15, $89, $00, $15, $89
@song0ch3loop:
@song0ref1028:
	.byte $83
@song0ref1029:
	.byte $00, $97
@song0ref1031:
	.byte $15, $8d, $00, $a5, $15, $8d, $00, $a5, $15, $8d, $00, $a5
	.byte $41, $0c
	.word @song0ref1031
@song0ref1046:
	.byte $15, $8d, $00, $a5, $15, $89, $00, $15, $89
	.byte $41, $0f
	.word @song0ref1028
	.byte $41, $0c
	.word @song0ref1031
	.byte $41, $09
	.word @song0ref1046
	.byte $41, $0f
	.word @song0ref1028
	.byte $41, $0c
	.word @song0ref1031
	.byte $41, $09
	.word @song0ref1046
	.byte $41, $0f
	.word @song0ref1028
	.byte $41, $09
	.word @song0ref1031
	.byte $89, $00, $15, $8d, $00, $a5
	.byte $41, $09
	.word @song0ref1018
	.byte $00, $15, $89
	.byte $41, $0f
	.word @song0ref1028
	.byte $15, $89, $00, $15, $8d
	.byte $41, $0e
	.word @song0ref1029
	.byte $15, $89, $00, $15, $89
	.byte $41, $0f
	.word @song0ref1028
	.byte $15, $89, $00, $15, $8d
	.byte $41, $0b
	.word @song0ref1029
	.byte $89, $00
	.byte $41, $09
	.word @song0ref1018
	.byte $00, $15, $89, $83, $00, $97
@song0ref1129:
	.byte $96
@song0ref1130:
	.byte $1e, $85, $00, $83, $1e, $85, $00, $9f, $1e, $85, $00, $83, $1e, $85, $00, $83, $1e, $85, $00, $91
	.byte $41, $14
	.word @song0ref1130
	.byte $41, $14
	.word @song0ref1130
	.byte $1e, $85, $00, $83, $1e, $85, $00, $9f, $8e, $15, $8d, $00, $87, $9d
	.byte $41, $14
	.word @song0ref1129
	.byte $41, $14
	.word @song0ref1130
	.byte $41, $13
	.word @song0ref1130
	.byte $ad, $8e
	.byte $41, $09
	.word @song0ref1018
	.byte $42
	.word @song0ch3loop
@song0ch4:
	.byte $01, $ff, $dd, $01, $ed, $01, $b5, $02, $b5, $01, $ff, $dd, $01, $ed, $01, $b5, $02, $99, $02, $8b, $02, $8b
@song0ch4loop:
@song0ref1210:
	.byte $01, $99, $02, $8b, $01, $99, $01, $8b, $02, $99, $01, $99, $02, $99, $01, $8b, $01, $8b, $02, $99
	.byte $41, $13
	.word @song0ref1210
	.byte $8b, $02, $8b
	.byte $41, $14
	.word @song0ref1210
	.byte $41, $13
	.word @song0ref1210
	.byte $8b, $02, $8b
	.byte $41, $14
	.word @song0ref1210
	.byte $41, $0f
	.word @song0ref1210
	.byte $99, $02, $8b, $02, $8b
	.byte $41, $14
	.word @song0ref1210
	.byte $41, $09
	.word @song0ref1210
	.byte $8b, $02, $8b, $01, $99, $01, $8b, $02, $8b, $01, $8b, $02, $8b, $02, $8b, $02, $8b
	.byte $41, $0d
	.word @song0ref1210
@song0ref1282:
	.byte $8b, $01, $99, $01, $8b, $02, $8b, $02, $8b
	.byte $41, $0d
	.word @song0ref1210
	.byte $41, $09
	.word @song0ref1282
	.byte $41, $0d
	.word @song0ref1210
	.byte $41, $09
	.word @song0ref1282
	.byte $41, $09
	.word @song0ref1210
	.byte $41, $09
	.word @song0ref1282
	.byte $01, $8b, $02, $8b, $02, $8b, $02, $8b, $01, $b5, $01, $ed, $01, $ed, $01, $ed, $01, $99, $02, $99, $01, $b5, $01, $ed
	.byte $01, $ed, $01, $d1, $01, $8b, $01, $8b, $02, $99, $02, $8b, $02, $8b, $42
	.word @song0ch4loop
